BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "balena-rockpi"
BBFILE_PATTERN_balena-rockpi := "^${LAYERDIR}/"
BBFILE_PRIORITY_balena-rockpi = "1337"

LAYERSERIES_COMPAT_balena-rockpi = "scarthgap"

# override what the BSP defines in the machine conf because we use the Radxa CM3 on a RPi Compute Module 4 IO Board
KERNEL_DEVICETREE:radxa-cm3-io-rk3566 = "rockchip/rk3566-radxa-cm3-rpi-cm4-io.dtb"
UBOOT_MACHINE:radxa-cm3-io-rk3566 = "radxa-cm3-rpi-cm4-io-rk3566_defconfig"

# we need only the initramfs kernel in the rootfs so we remove the non-initramfs version
MACHINE_ESSENTIAL_EXTRA_RDEPENDS:remove = "kernel-image"

# remove the extlinux package and only add it via IMAGE_INSTALL for the internal image
MACHINE_ESSENTIAL_EXTRA_RDEPENDS:remove = "u-boot-extlinux"

# the BSP sets this as fitImage but we don't use it because the flasher has problems when booting with an older u-boot and a fitImage kernel type
KERNEL_IMAGETYPE = "Image"
